version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: pastebin-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3132
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: pastebin-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      APP_HOST: http://185.104.249.56
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 3132

volumes:
  pgdata:
